# Generated by Django 4.2.5 on 2024-12-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustles', '0002_employer_boss_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_location',
            field=models.CharField(max_length=430),
        ),
    ]
