# Generated by Django 4.2.5 on 2024-12-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustles', '0004_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.CharField(max_length=420, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='employee',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
