# Generated by Django 4.2.5 on 2024-12-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hustles', '0005_application_skills_alter_application_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
