# Generated by Django 4.2.5 on 2024-12-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustles', '0006_remove_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
