# Generated by Django 4.2.5 on 2024-12-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustles', '0007_alter_application_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
