# Generated by Django 4.2.5 on 2024-12-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustles', '0008_application_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('No Response yet', 'No response yet')], default='No Response yet', max_length=20),
        ),
    ]
