# Generated by Django 4.2.5 on 2024-12-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustles', '0010_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'pending')], default='Pending', max_length=20, null=True),
        ),
    ]
